export type Project = {
  num: string;
  index: string;
  name: string;
  category: string;
  description: string;
  stack: {
    name: string;
  }[];
  fe: {
    name: string;
  }[];
  be?: {
    name: string;
  }[];
  others: {
    name: string;
  }[];
  image: string;
  live: string;
  github1: string;
  github2?: string;
};

// type Projects = Project[];

export default [
  {
    num: "01",
    index: "01",
    name: "Construction building",
    category: "frontend",
    description:
      "A Construction Build web experience — a sleek, modern platform developed with Next.js for high performance and Framer Motion to bring every interaction to life. From smooth scrolling to animated section reveals, . As users explore the site, they’re greeted with subtle transitions, sliding text, and fade-ins that enhance the narrative without overwhelming the user",
    stack: [
      { name: "Next.js" },
      { name: "React" },
      { name: "Tailwind CSS" },
      { name: "Framer-motion" },
      { name: "React-countup" },
      { name: "React-icons" },
      { name: "React-scroll" },
      { name: "Swiper" },
    ],
    fe: [
      { name: "Next.js" },
      { name: "React" },
      { name: "Tailwind CSS" },
      { name: "Framer-motion" },
      { name: "React-countup" },
      { name: "React-icons" },
      { name: "React-scroll" },
      { name: "Swiper" },
    ],
    others: [{ name: "Vercel" }],
    image: "/assets/construction.jpg",
    live: "https://construction-lilac-two.vercel.app/",
    github1: "https://github.com/mohammadrida990/construction",
  },
  {
    num: "02",
    index: "06",
    name: "Blog system",
    category: "fullstack",
    description:
      "A project act as blog system that shows posts, comments, likes and manage your post lists after authentication",
    stack: [
      { name: "Next.js" },
      { name: "Nest.js" },
      { name: "React" },
      { name: "GraphQl" },
      { name: "Prisma" },
      { name: "SqlLite" },
      { name: "Turborepo" },
      { name: "Supabase" },
      { name: "Tailwind CSS" },
      { name: "Shadcn-ui" },
      { name: "Hero icons" },
      { name: "Framer-motion" },
      { name: "Zod" },
      { name: "Argon2" },
      { name: "Jwt" },
      { name: "Nestjs-passport" },
      { name: "Tanstack-react-query" },
    ],
    fe: [
      { name: "Next.js" },
      { name: "React" },
      ,
      { name: "Tailwind CSS" },
      { name: "Shadcn-ui" },
      { name: "Hero icons" },
      { name: "Framer-motion" },
      { name: "Zod" },
      { name: "Tanstack-react-query" },
    ],
    be: [
      { name: "Nest.js" },
      { name: "GraphQl" },
      { name: "Prisma" },
      { name: "SqlLite" },
      { name: "Argon2" },
      { name: "Jwt" },
      { name: "Nestjs-passport" },
    ],
    others: [
      { name: "Supabase" },
      { name: "Turborepo" },
      { name: "Render" },
      { name: "Vercel" },
    ],
    image: "/assets/blog.png",
    live: "https://blog-system-pi.vercel.app/",
    github1: "https://github.com/mohammadrida990/blog-system",
  },
  {
    num: "03",
    index: "02",
    name: "Coffee shop",
    category: "frontend",
    description:
      "This project is a coffee shop as a creative exploration of modern web animations using tools like Framer Motion, GSAP and Tailwind CSS. It focuses purely on experimenting with scroll-based animations, transitions, and layout interactions. The goal was not to build a complete product, but to test how elements can move, transform, and respond to user actions in smooth and visually engaging ways.",
    stack: [
      { name: "Next.js" },
      { name: "React" },
      { name: "Tailwind CSS" },
      { name: "Framer-motion" },
      { name: "GSAP" },
      { name: "Locomotive-scroll" },
      { name: "gsap-react" },
    ],
    fe: [
      { name: "Next.js" },
      { name: "React" },
      { name: "Tailwind CSS" },
      { name: "Framer-motion" },
      { name: "GSAP" },
      { name: "Locomotive-scroll" },
      { name: "gsap-react" },
    ],
    others: [{ name: "Vercel" }],
    image: "/assets/coffeeShop.jpg",
    live: "https://coffee-shop-two-red.vercel.app/",
    github1: "https://github.com/mohammadrida990/coffee-shop",
  },
  {
    num: "04",
    index: "12",
    name: "E-commerce",
    category: "fullstack",
    description:
      "Small ecommerce project that shows some products, select products, add to cart and checkout",
    stack: [
      { name: "Next.js" },
      { name: "Nest.js" },
      { name: "Tailwind CSS" },
      { name: "Shadcn-ui" },
      { name: "Hero icons" },
      { name: "PostgreSQL" },
      { name: "Stripe" },
      { name: "Zustand" },
    ],
    fe: [
      { name: "Next.js" },
      { name: "Tailwind CSS" },
      { name: "Shadcn-ui" },
      { name: "Hero icons" },
    ],
    be: [{ name: "Nest.js" }, { name: "PostgreSQL" }],
    others: [{ name: "Stripe" }, { name: "Vercel" }],
    image: "/assets/eccomerce.png",
    live: "",
    github1: "https://github.com/mohammadrida990/eccomerce_frontend",
    github2: "https://github.com/mohammadrida990/ecommerce-backend",
  },
  {
    num: "05",
    index: "11",
    name: "Scrolling animation",
    category: "frontend",
    description:
      "This project is a creative exploration of modern web animations using tools like Framer Motion and Tailwind CSS. It focuses purely on experimenting with scroll-based animations, transitions, and layout interactions. The goal was not to build a complete product, but to test how elements can move, transform, and respond to user actions in smooth and visually engaging ways.",
    stack: [
      { name: "Next.js" },
      { name: "React" },
      { name: "Tailwind CSS" },
      { name: "Framer-motion" },
      { name: "GSAP" },
    ],
    fe: [
      { name: "Next.js" },
      { name: "React" },
      { name: "Tailwind CSS" },
      { name: "Framer-motion" },
      { name: "GSAP" },
    ],
    image: "/assets/scroll.png",
    live: "https://scrolling-animation-six.vercel.app/",
    github1: "https://github.com/mohammadrida990/scrolling-animation",
  },
  {
    num: "06",
    index: "05",
    name: "Rida Portfolio",
    category: "frontend",
    description:
      "My portfolio project that describe my resume with skills, experience education and my contact information and social media.",
    stack: [
      { name: "React" },
      { name: "Next.js" },
      { name: "Tailwind CSS" },
      { name: "Shadcn-ui" },
      { name: "Framer-motion" },
      { name: "React-countup" },
      { name: "React-icons" },
    ],
    fe: [
      { name: "React" },
      { name: "Next.js" },
      { name: "Tailwind CSS" },
      { name: "Shadcn-ui" },
      { name: "Framer-motion" },
      { name: "React-countup" },
      { name: "React-icons" },
    ],
    image: "/assets/porfolio.png",
    live: "https://rida-portfolio-five.vercel.app/",
    github1: "https://github.com/mohammadrida990/rida-portfolio",
  },
  {
    num: "07",
    index: "08",
    name: "Admin dashboard",
    category: "fullstack",
    description:
      "Small admin dashboard project that shows some analysis about users and products with ability to add users and products with info. with ability to login using username and password or login with google",
    stack: [
      { name: "Next.js" },
      { name: "React.js" },
      { name: "Tailwind CSS" },
      { name: "Shadcn-ui" },
      { name: "Hero icons" },
      { name: "Recharts" },
      { name: "SWR" },
      { name: "Date-fns" },
      { name: "PostgreSQL" },
      { name: "Bcrypt" },
      { name: "Prisma" },
    ],
    fe: [
      { name: "Next.js" },
      { name: "React.js" },
      { name: "Tailwind CSS" },
      { name: "Shadcn-ui" },
      { name: "Hero icons" },
      { name: "Recharts" },
      { name: "SWR" },
      { name: "Date-fns" },
    ],
    be: [{ name: "Prisma" }, { name: "PostgreSQL" }, { name: "Bcrypt" }],
    others: [{ name: "Neon" }],
    image: "/assets/admin-dashboard.jpg",
    live: "https://admin-dashboard-puce-nine-24.vercel.app/dashboard",
    github1: "https://github.com/mohammadrida990/admin-dashboard",
  },
  {
    num: "08",
    index: "09",
    name: "Animation sliders",
    category: "frontend",
    description:
      "This small project is a web experience built with React, focusing on smooth, engaging animations powered by GSAP and Framer Motion. It blends the precision and performance of GSAP with the intuitive React-based animation capabilities of Framer Motion to deliver dynamic UI transitions, fluid interactions, and immersive motion design. This combination enables us to create highly responsive and visually compelling interfaces that enhance user engagement and bring the application to life.",
    stack: [
      { name: "React" },
      { name: "Tailwind CSS" },
      { name: "Framer-motion" },
      { name: "Gsap" },
      { name: "React-icons" },
    ],
    fe: [
      { name: "React" },
      { name: "Tailwind CSS" },
      { name: "Framer-motion" },
      { name: "Gsap" },
      { name: "React-icons" },
    ],
    others: [{ name: "Vercel" }],
    image: "/assets/animation-sliders.jpg",
    live: "https://animation-sliders.vercel.app/",
    github1: "https://github.com/mohammadrida990/animation-sliders",
  },
  {
    num: "09",
    index: "07",
    name: "Smokers vibes",
    category: "frontend",
    description:
      "This small project is a web experience built with React, focusing on smooth, engaging animations powered by GSAP and Framer Motion. It blends the precision and performance of GSAP with the intuitive React-based animation capabilities of Framer Motion to deliver dynamic UI transitions, fluid interactions, and immersive motion design. This combination enables us to create highly responsive and visually compelling interfaces that enhance user engagement and bring the application to life.",
    stack: [
      { name: "React" },
      { name: "Tailwind CSS" },
      { name: "Framer-motion" },
      { name: "Gsap" },
      { name: "Locomotive-scroll" },
      { name: "React-router-dom" },
    ],
    fe: [
      { name: "React" },
      { name: "Tailwind CSS" },
      { name: "Framer-motion" },
      { name: "Gsap" },
      { name: "Locomotive-scroll" },
      { name: "React-router-dom" },
    ],
    others: [{ name: "Vercel" }],
    image: "/assets/smokers.jpg",
    live: "https://smokers.vercel.app/",
    github1: "https://github.com/mohammadrida990/smokers",
  },
  {
    num: "10",
    index: "10",
    name: "Movies store",
    category: "fullstack",
    description:
      "Small movies store that shows list of trending movies with ability add to watch later. with ability to login using username and password or login with google",
    stack: [
      { name: "Next.js" },
      { name: "React.js" },
      { name: "Tailwind CSS" },
      { name: "React-icons" },
      { name: "SWR" },
      { name: "PostgreSQL" },
      { name: "Bcrypt" },
      { name: "Prisma" },
      { name: "Zustand" },
      { name: "Next-auth" },
      { name: "Lodash" },
      { name: "Axios" },
      { name: "Prisma/client" },
    ],
    fe: [
      { name: "Next.js" },
      { name: "React.js" },
      { name: "Tailwind CSS" },
      { name: "React-icons" },
      { name: "SWR" },
      { name: "Zustand" },
      { name: "Next-auth" },
      { name: "Lodash" },
      { name: "Axios" },
      { name: "Prisma/client" },
    ],
    be: [{ name: "Prisma" }, { name: "PostgreSQL" }, { name: "Bcrypt" }],
    others: [{ name: "Neon" }, { name: "vercel" }],
    image: "/assets/movies-store.jpg",
    live: "https://movies-store-th5o.vercel.app/",
    github1: "https://github.com/mohammadrida990/movies-store",
  },
  {
    num: "11",
    index: "03",
    name: "E-Commerce admin store",
    category: "fullstack",
    description:
      "NextCommerce Admin is a powerful and intuitive e-commerce admin dashboard built with Next.js and PostgreSQL, designed to give store owners and administrators full control over their product catalog. With secure Google authentication, admins can log in and manage multiple stores, organize products into categories, and apply filters for easy navigation and management. Acting as a lightweight CMS, the platform enables seamless creation, editing, and organization of products, making it ideal for businesses looking to streamline their e-commerce operations through a modern, scalable, and user-friendly interface.",
    stack: [
      { name: "Next.js" },
      { name: "React.js" },
      { name: "Tailwind CSS" },
      { name: "PostgreSQL" },
      { name: "Zustand" },
      { name: "Axios" },
      { name: "Prisma/client" },
      { name: "Next-themes" },
      { name: "Tanstack/react-table" },
      { name: "Stripe" },
      { name: "Recharts" },
      { name: "React-hot-toast" },
      { name: "Lucide-react" },
      { name: "Date-fns" },
      { name: "Supabase" },
      { name: "Radix-ui" },
      { name: "Shadcn-ui" },
      { name: "Zod" },
      { name: "React-hook-form" },
      { name: "Clerk" },
    ],
    fe: [
      { name: "Next.js" },
      { name: "React.js" },
      { name: "Tailwind CSS" },
      { name: "Zustand" },
      { name: "Next-themes" },
      { name: "Tanstack/react-table" },
      { name: "Recharts" },
      { name: "React-hot-toast" },
      { name: "Lucide-react" },
      { name: "Radix-ui" },
      { name: "Shadcn-ui" },
      { name: "Zod" },
      { name: "React-hook-form" },
      { name: "Clerk" },
      { name: "Axios" },
    ],
    be: [
      { name: "PostgreSQL" },
      { name: "Prisma/client" },
      { name: "Tanstack/react-table" },
      { name: "Stripe" },
      { name: "Date-fns" },
      { name: "Supabase" },
    ],
    others: [{ name: "Neon" }, { name: "Vercel" }],
    image: "/assets/ecommerce-admin.jpg",
    live: "https://ecommerce-admin-six-green.vercel.app/",
    github1: "https://github.com/mohammadrida990/ecommerce-admin",
  },
  {
    num: "12",
    index: "04",
    name: "E-Commerce client store",
    category: "frontend",
    description:
      "NextCommerce Client is a sleek and responsive e-commerce frontend application built with Next.js, designed to deliver a fast and seamless shopping experience. Customers can browse a wide range of products, apply category-based filters, and view detailed product pages. The platform features a fully functional shopping cart, allowing users to manage their selections before securely checking out using Stripe for payments. Optimized for performance and user experience, this client-side application complements the admin dashboard, providing a complete e-commerce solution from browsing to checkout.",
    stack: [
      { name: "Next.js" },
      { name: "React.js" },
      { name: "Tailwind CSS" },
      { name: "Zustand" },
      { name: "Axios" },
      { name: "React-hot-toast" },
      { name: "Lucide-react" },
      { name: "@headlessui/react" },
      { name: "query-string" },
    ],
    fe: [
      { name: "Next.js" },
      { name: "React.js" },
      { name: "Tailwind CSS" },
      { name: "Zustand" },
      { name: "Axios" },
      { name: "React-hot-toast" },
      { name: "Lucide-react" },
      { name: "@headlessui/react" },
      { name: "Query-string" },
    ],
    others: [{ name: "Vercel" }],
    image: "/assets/ecommerce-client.jpg",
    live: "https://ecommerce-store-rho-three.vercel.app/",
    github1: "https://github.com/mohammadrida990/ecommerce-store",
  },
] as Project[];
